// Generated by CoffeeScript 1.10.0
(function(W) {
  return W.plugin("wufooForm", function(video, options) {
    var showForm;
    if (options == null) {
      options = {};
    }
    showForm = function() {
      return $('.open-lightbox').trigger('click');
    };
    video.bind("end", showForm);
    return {};
  });
})(Wistia);
