// Generated by CoffeeScript 1.10.0
(function(W) {
  return W.plugin("wufooForm", function(video, options) {
    var showForm;
    if (options == null) {
      options = {};
    }
    showForm = function() {
      var wufooForm;
      wufooForm = $("#wufoo-m1vmnn3l0x4bbg4");
      return wufooForm.show();
    };
    video.bind("end", showForm);
    return {};
  });
})(Wistia);
