// Generated by CoffeeScript 1.6.2
var VideoFoam,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

VideoFoam = (function() {
  function VideoFoam() {
    this.updateOutput = __bind(this.updateOutput, this);
    this.debounceUpdateOutput = __bind(this.debounceUpdateOutput, this);
    var _this = this;

    this.resizeable = false;
    this.iframeApiString = "\n<script src='//fast.wistia.com/static/iframe-api-v1.js'></script>";
    $("#configure").on("keyup", "input[type=text], textarea", function() {
      return _this.debounceUpdateOutput();
    }).on("click", ":radio,:checkbox", function() {
      return _this.debounceUpdateOutput();
    }).on("change", "select", function() {
      return _this.debounceUpdateOutput();
    });
  }

  VideoFoam.prototype.debounceUpdateOutput = function() {
    clearTimeout(this.updateOutputTimeout);
    return this.updateOutputTimeout = setTimeout(this.updateOutput, 500);
  };

  VideoFoam.prototype.updateOutput = function() {
    var isIframe, isPopover;

    clearTimeout(this.updateOutputTimeout);
    this.sourceEmbedCode = Wistia.EmbedCode.parse($("#source_embed_code").val());
    this.outputEmbedCode = Wistia.EmbedCode.parse($("#source_embed_code").val());
    if ($("#mode_all").is(":checked")) {
      return $("#output_embed_code").val("<script src=\"//fast.wistia.com/static/embed_shepherd-v1.js\"></script>\n<script>\nwistiaEmbeds.onFind(function(video) {\n  video.ready(function() {\n    video.params.videoFoam = true;\n  });\n});\n</script>");
    } else if (this.sourceEmbedCode && this.sourceEmbedCode.isValid()) {
      isIframe = Wistia.EmbedCode.isIframe(this.sourceEmbedCode);
      isPopover = Wistia.EmbedCode.isPopover(this.sourceEmbedCode);
      this.outputEmbedCode.setOption("videoFoam", true);
      if (isIframe || isPopover) {
        $("#output_embed_code").val(this.outputEmbedCode.toString() + this.iframeApiString);
      } else {
        $("#output_embed_code").val(this.outputEmbedCode);
      }
      this.outputEmbedCode.previewInElem("preview");
      $("#try").show();
      if (!this.resizeable) {
        this.addResizableTo($("#draggable_wrapper"));
        return this.resizeable = true;
      }
    } else {
      $("#output_embed_code").val("Hmm, that embed code doesn't look right. Maybe our dog chewed on it?");
      return $("#preview").html('<div id="placeholder_preview">Your video here</div>');
    }
  };

  VideoFoam.prototype.addResizableTo = function(elem) {
    return elem.addClass('foamed').draggable().resizable();
  };

  return VideoFoam;

})();

window.setupLabInterface = function($) {
  return $(function() {
    window.videoFoam = new VideoFoam();
    if (!Wistia.localStorage("videoFoam.cleared")) {
      showExample();
      $(".show_example_text").hide();
      $(".clear_example_text").show();
    } else {
      $(".show_example_text").show();
      $(".clear_example_text").hide();
    }
    $("#clear_example").click(function(event) {
      event.preventDefault();
      resetInterface();
      $(".show_example_text").show();
      $(".clear_example_text").hide();
      return Wistia.localStorage("videoFoam.cleared", true);
    });
    $("#show_example").click(function(event) {
      event.preventDefault();
      showExample();
      $(".show_example_text").hide();
      $(".clear_example_text").show();
      return Wistia.localStorage("videoFoam.cleared", false);
    });
    $("#mode_all").click(function() {
      $(".paste_embed_code.jamjar").hide();
      $(".instructions.jamjar .for_all").show();
      $(".instructions.jamjar .for_one").hide();
      return $("#preview_area").hide();
    });
    return $("#mode_one").click(function() {
      $(".paste_embed_code.jamjar").show();
      $(".instructions.jamjar .for_all").hide();
      $(".instructions.jamjar .for_one").show();
      return $("#preview_area").show();
    });
  });
};

window.resetInterface = function() {
  $("#source_embed_code").val("").keyup().change();
  $("#mode_all").removeAttr("checked").trigger("click").change();
  return $("#mode_one").attr("checked", "checked").trigger("click").change();
};

window.showExample = function() {
  resetInterface();
  return $("#source_embed_code").val("<iframe src=\"http://fast.wistia.net/embed/iframe/atnj7kek19?playerColor=81b7db&version=v1&videoHeight=304&videoWidth=540\" allowtransparency=\"true\" frameborder=\"0\" scrolling=\"no\" class=\"wistia_embed\" name=\"wistia_embed\" width=\"540\" height=\"304\"></iframe>").keyup().change();
};

window.setupLabInterface(jQuery);
