// Generated by CoffeeScript 1.5.0

Wistia.plugin('prez', function(video, options) {
  var height, position, prezElem, slideChange, speakerDeck, update, width;
  position = options.position || 'right';
  width = options.width || video.width();
  height = options.height || video.height();
  prezElem = document.createElement('div');
  prezElem.innerHTML = "<div class='speakerdeck-embed' data-id='" + options.speakerDeckId + "'></div>";
  prezElem.style.width = "" + width + "px";
  prezElem.style.height = "" + height + "px";
  video.grid[position].appendChild(prezElem);
  video.fit();
  slideChange = function(slide) {
    return console.log("changed slide to: " + slide);
  };
  speakerDeck = null;
  window.onSpeakerDeckPlayerReady = function(s) {
    speakerDeck = s;
    return speakerDeck.on('change', function(slide) {
      return slideChange(slide.number);
    });
  };
  Wistia.remote.script('//speakerdeck.com/assets/embed.js');
  video.bind('secondchange', function(s) {
    if (s % 5 === 0) {
      return speakerDeck.nextSlide();
    }
  });
  update = function(options) {
    return console.log("updated prez");
  };
  return {
    update: update
  };
});
