// Generated by CoffeeScript 1.6.3
var AgeRestriction,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

window.jsFileName = "plugin.js";

window.jsProductionPath = "fast.wistia.com/labs/age-restriction";

AgeRestriction = (function() {
  function AgeRestriction() {
    this.updatePreview = __bind(this.updatePreview, this);
    this.updateOutputEmbedCode = __bind(this.updateOutputEmbedCode, this);
    var _this = this;
    this.previewEmbedded = false;
    this.change = false;
    this.exampleEmbedCode = '<div id="wistia_r13i3i9qye" class="wistia_embed" style="width:640px;height:360px;"></div><script charset="ISO-8859-1" src="http://fast.wistia.com/assets/external/E-v1.js"></script><script>wistiaEmbed = Wistia.embed("r13i3i9qye");</script>';
    $("#source_embed_code").on("keyup", function() {
      _this.previewEmbedded = false;
      _this.change = false;
      return _this.debounceUpdates();
    });
    $("a[name=remove_all]").on('click', function(e) {
      e.preventDefault();
      return _this.clearAll();
    });
    $("a[name=see_example]").on('click', function(e) {
      e.preventDefault();
      return _this.setupExample();
    });
    $("a[name=reset]").on('click', function(e) {
      e.preventDefault();
      _this.change = false;
      _this.previewEmbedded = false;
      return _this.debounceUpdates();
    });
    $("#configure input[type=number]").on("change", function() {
      _this.change = true;
      return _this.debounceUpdates();
    });
    $("#configure input[type=radio]").on("change", function() {
      _this.change = true;
      return _this.debounceUpdates();
    });
  }

  AgeRestriction.prototype.setupExample = function() {
    $("#source_embed_code").val(this.exampleEmbedCode);
    this.previewEmbedded = false;
    this.change = false;
    return this.debounceUpdates();
  };

  AgeRestriction.prototype.clearAll = function() {
    $("#source_embed_code").val("");
    this.previewEmbedded = false;
    this.change = false;
    return this.debounceUpdates();
  };

  AgeRestriction.prototype.debounceUpdates = function() {
    var updateOutputTimeout;
    clearTimeout("updateOutputTimeout");
    return updateOutputTimeout = setTimeout(this.updateOutputEmbedCode, 100);
  };

  AgeRestriction.prototype.updateOutputEmbedCode = function() {
    this.sourceEmbedCode = Wistia.EmbedCode.parse($("#source_embed_code").val());
    this.outputEmbedCode = Wistia.EmbedCode.parse($("#source_embed_code").val());
    if (this.sourceEmbedCode && this.sourceEmbedCode.isValid()) {
      this.minimumAge = this.getMinimumAge();
      this.type = this.getType();
      this.outputEmbedCode.setOption("plugin.ageRestriction.src", pluginSrc(this.sourceEmbedCode));
      this.outputEmbedCode.setOption("plugin.ageRestriction.type", this.type);
      this.outputEmbedCode.setOption("plugin.ageRestriction.minimumAge", this.minimumAge);
      $("#output_embed_code").val(this.outputEmbedCode.toString());
      return this.updatePreview();
    } else {
      $("#output_embed_code").val("Please enter a valid Wistia embed code.");
      return $("#preview").html("<div id=\"placeholder_preview\">Your video here</div>");
    }
  };

  AgeRestriction.prototype.updatePreview = function() {
    var _this = this;
    return Wistia.timeout("updatePreview", function() {
      if (_this.change) {
        window.previewEmbed.plugin.ageRestriction.updateType(_this.type);
        return window.previewEmbed.plugin.ageRestriction.updateAge(_this.minimumAge);
      } else if (!_this.previewEmbedded) {
        return _this.outputEmbedCode.previewInElem("preview", {
          type: "api"
        }, function() {
          var _base, _base1;
          if (typeof (_base = window.previewEmbed).plugin === "function") {
            _base.plugin(ageRestriction.updateType(_this.type));
          }
          if (typeof (_base1 = window.previewEmbed).plugin === "function") {
            _base1.plugin(ageRestriction.updateAge(_this.minimumAge));
          }
          return _this.previewEmbedded = true;
        });
      }
    }, 100);
  };

  AgeRestriction.prototype.waitFor = function(cond, timeout) {
    var fn, result, startTime, timeoutId;
    if (timeout == null) {
      timeout = 5000;
    }
    result = new Wistia.StopGo();
    timeoutId = Wistia.seqId();
    startTime = new Date().getTime();
    fn = function() {
      if (new Date().getTime() - startTime > 5000) {
        return typeof console !== "undefined" && console !== null ? console.log('Condition ', cond, ' never came true') : void 0;
      } else if (cond()) {
        return result.go();
      } else {
        return Wistia.timeout(timeoutId, fn, 100);
      }
    };
    fn();
    return result;
  };

  AgeRestriction.prototype.getMinimumAge = function() {
    return parseInt($("#minimum-age").val());
  };

  AgeRestriction.prototype.getType = function() {
    if ($("input#age").is(':checked')) {
      return "age";
    } else if ($("input#dob").is(':checked')) {
      return "dob";
    }
  };

  return AgeRestriction;

})();

window.setupLabInterface = function($) {
  return $(function() {
    window.ageRestriction = new AgeRestriction();
    if (!Wistia.localStorage("ageRestriction.cleared")) {
      showExample();
      $(".show_example_text").hide();
      $(".clear_example_text").show();
    } else {
      $(".show_example_text").show();
      $(".clear_example_text").hide();
    }
    $("#clear_example").click(function(event) {
      event.preventDefault();
      resetInterface();
      $(".show_example_text").show();
      $(".clear_example_text").hide();
      return Wistia.localStorage("ageRestriction.cleared", true);
    });
    return $("#show_example").click(function(event) {
      event.preventDefault();
      showExample();
      $(".show_example_text").hide();
      $(".clear_example_text").show();
      return Wistia.localStorage("ageRestriction.cleared", false);
    });
  });
};

window.resetInterface = function() {
  return ageRestriction.clearAll();
};

window.showExample = function() {
  return ageRestriction.setupExample();
};

setupLabInterface(jQuery);
