// Generated by CoffeeScript 1.6.2
(function(W) {
  var bindEvent;
  bindEvent = function(elem, event, fn) {
    return elem.addEventListener(event, fn, false);
  };
  return W.plugin("videoInEmail", function(video, options) {
    if (options == null) {
      options = {};
    }
  });
})(Wistia);
