// Generated by CoffeeScript 1.6.2
var VideoInEmail,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

VideoInEmail = (function() {
  function VideoInEmail() {
    this.outputVideoCode = __bind(this.outputVideoCode, this);
    this.updateVideoCode = __bind(this.updateVideoCode, this);
    this.updatePreview = __bind(this.updatePreview, this);
    this.updateOutputEmbedCode = __bind(this.updateOutputEmbedCode, this);
    var _this = this;
    this.previewEmbedded = false;
    this.change = false;
    this.exampleEmbedCode = "<iframe src=\"//fast.wistia.net/embed/iframe/7phpe910v3\" allowtransparency=\"true\" frameborder=\"0\" scrolling=\"no\" class=\"wistia_embed\" name=\"wistia_embed\" allowfullscreen mozallowfullscreen webkitallowfullscreen oallowfullscreen msallowfullscreen width=\"600\" height=\"338\"></iframe>";
    $("#source_embed_code").on("keyup", function() {
      _this.previewEmbedded = false;
      _this.change = false;
      return _this.debounceUpdates();
    });
    $("#video_width").on("keyup", function() {
      _this.previewEmbedded = false;
      _this.change = false;
      return _this.debounceUpdates();
    });
    $("#fallback_link").on("keyup", function() {
      _this.previewEmbedded = false;
      _this.change = false;
      return _this.debounceUpdates();
    });
    $("a[name=remove_all]").on('click', function(e) {
      e.preventDefault();
      return _this.clearAll();
    });
    $("a[name=see_example]").on('click', function(e) {
      e.preventDefault();
      return _this.setupExample();
    });
    $("a[name=reset]").on('click', function(e) {
      e.preventDefault();
      _this.change = false;
      _this.previewEmbedded = false;
      return _this.debounceUpdates();
    });
    $("#configure input[type=number]").on("change", function() {
      _this.change = true;
      return _this.debounceUpdates();
    });
    $("#configure input[type=radio]").on("change", function() {
      _this.change = true;
      return _this.debounceUpdates();
    });
    $("#configure textarea").on("change", function() {
      _this.change = true;
      return _this.debounceUpdates();
    });
  }

  VideoInEmail.prototype.setupExample = function() {
    $("#source_embed_code").val(this.exampleEmbedCode);
    $("#video_width").val(600);
    $("#fallback_link").val("https://home.wistia.com/medias/7phpe910v3");
    this.previewEmbedded = false;
    this.change = false;
    return this.debounceUpdates();
  };

  VideoInEmail.prototype.clearAll = function() {
    $("#source_embed_code").val("");
    this.previewEmbedded = false;
    this.change = false;
    return this.debounceUpdates();
  };

  VideoInEmail.prototype.debounceUpdates = function() {
    var updateOutputTimeout;
    clearTimeout("updateOutputTimeout");
    return updateOutputTimeout = setTimeout(this.updateOutputEmbedCode, 100);
  };

  VideoInEmail.prototype.updateOutputEmbedCode = function() {
    this.sourceEmbedCode = Wistia.EmbedCode.parse($("#source_embed_code").val());
    this.outputEmbedCode = Wistia.EmbedCode.parse($("#source_embed_code").val());
    if (this.sourceEmbedCode && this.sourceEmbedCode.isValid()) {
      this.width = this.getVideoWidth();
      $("#output_embed_code").val(this.outputEmbedCode.toString());
      this.updatePreview();
      return this.updateVideoCode();
    } else {
      $("#output_embed_code").val("Please enter a valid Wistia embed code.");
      return $("#preview").html("<div id=\"placeholder_preview\">Your video here</div>");
    }
  };

  VideoInEmail.prototype.updatePreview = function() {
    var _this = this;
    return Wistia.timeout("updatePreview", function() {
      if (_this.change) {

      } else if (!_this.previewEmbedded) {
        return _this.outputEmbedCode.previewInElem("preview", {
          type: "api"
        }, function() {
          return _this.previewEmbedded = true;
        });
      }
    }, 100);
  };

  VideoInEmail.prototype.updateVideoCode = function() {
    var _this = this;
    Wistia.timeout("updateVideoCode", function() {
      var styles;
      $('#video_code').val(_this.outputVideoCode());
      styles = {
        height: '200px',
        width: '585px',
        'font-family': 'Courier'
      };
      return $('#video_code').css(styles);
    }, 100);
    Wistia.hashedId = Wistia.EmbedCode.parse($("#source_embed_code").val()).hashedId();
    return Wistia.remote.media("" + Wistia.hashedId, function(media) {
      Wistia.mp4Url = media.assets.iphone.url.replace('.bin', '/video.mp4');
      Wistia.posterUrl = media.assets.still.url;
      return Wistia.playerColor = media.embed_options.playerColor;
    });
  };

  VideoInEmail.prototype.outputVideoCode = function() {
    return "<video width=\"" + (this.getVideoWidth()) + "\" poster=\"" + (this.getPosterUrl()) + "\" controls=\"controls\">\n  <source src=\"" + (this.getVideoMp4()) + "\" type=\"video/mp4\"/>\n  <a href=\"" + (this.getFallbackLink()) + "\"><img src=\"" + (this.getPosterUrl().replace('.bin', '.jpg')) + "?image_play_button=true&image_play_button_color=" + (this.getPlayerColor()) + "&image_resize=" + (this.getVideoWidth()) + "\" width=\"" + (this.getVideoWidth()) + "\"/></a>\n</video>";
  };

  VideoInEmail.prototype.getVideoWidth = function() {
    return parseInt($("#video_width").val());
  };

  VideoInEmail.prototype.getFallbackLink = function() {
    return $("#fallback_link").val();
  };

  VideoInEmail.prototype.getVideoMp4 = function() {
    return Wistia.mp4Url;
  };

  VideoInEmail.prototype.getPosterUrl = function() {
    return Wistia.posterUrl;
  };

  VideoInEmail.prototype.getPlayerColor = function() {
    return Wistia.playerColor;
  };

  return VideoInEmail;

})();

window.setupLabInterface = function($) {
  return $(function() {
    window.videoInEmail = new VideoInEmail();
    if (!Wistia.localStorage("videoInEmail.cleared")) {
      showExample();
      $(".show_example_text").hide();
      $(".clear_example_text").show();
    } else {
      $(".show_example_text").show();
      $(".clear_example_text").hide();
    }
    $("#clear_example").click(function(event) {
      event.preventDefault();
      resetInterface();
      $(".show_example_text").show();
      $(".clear_example_text").hide();
      return Wistia.localStorage("videoInEmail.cleared", true);
    });
    return $("#show_example").click(function(event) {
      event.preventDefault();
      showExample();
      $(".show_example_text").hide();
      $(".clear_example_text").show();
      return Wistia.localStorage("videoInEmail.cleared", false);
    });
  });
};

window.resetInterface = function() {
  return videoInEmail.clearAll();
};

window.showExample = function() {
  return videoInEmail.setupExample();
};

setupLabInterface(jQuery);
