// Generated by CoffeeScript 1.6.2
var VideoInEmail,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

VideoInEmail = (function() {
  function VideoInEmail() {
    this.outputVideoCode = __bind(this.outputVideoCode, this);
    this.updateVideoCode = __bind(this.updateVideoCode, this);
    this.updatePreview = __bind(this.updatePreview, this);
    this.updateOutput = __bind(this.updateOutput, this);
    var _this = this;
    this.previewEmbedded = false;
    this.change = false;
    this.exampleEmbedCode = "<iframe src=\"//fast.wistia.net/embed/iframe/7phpe910v3\" allowtransparency=\"true\" frameborder=\"0\" scrolling=\"no\" class=\"wistia_embed\" name=\"wistia_embed\" allowfullscreen mozallowfullscreen webkitallowfullscreen oallowfullscreen msallowfullscreen width=\"600\" height=\"338\"></iframe>";
    $("#source_embed_code").on("keyup", function() {
      _this.previewEmbedded = false;
      _this.change = false;
      return _this.debounceUpdates();
    });
    $("#video_width").on("keyup", function() {
      _this.previewEmbedded = false;
      _this.change = false;
      _this.updateEmbedWidth($("#video_width").val());
      return _this.debounceUpdates();
    });
    $("#fallback_link").on("keyup", function() {
      _this.previewEmbedded = false;
      _this.change = false;
      return _this.debounceUpdates();
    });
    $("a[name=remove_all]").on('click', function(e) {
      e.preventDefault();
      return _this.clearAll();
    });
    $("a[name=see_example]").on('click', function(e) {
      e.preventDefault();
      return _this.setupExample();
    });
    $("a[name=reset]").on('click', function(e) {
      e.preventDefault();
      _this.change = false;
      _this.previewEmbedded = false;
      return _this.debounceUpdates();
    });
    $("#configure input[type=number]").on("change", function() {
      _this.change = true;
      return _this.debounceUpdates();
    });
    $("#configure input[type=radio]").on("change", function() {
      _this.change = true;
      return _this.debounceUpdates();
    });
    $("#configure textarea").on("change", function() {
      _this.change = true;
      return _this.debounceUpdates();
    });
  }

  VideoInEmail.prototype.setupExample = function() {
    $("#source_embed_code").val(this.exampleEmbedCode);
    $("#video_width").val(600);
    $("#fallback_link").val("https://home.wistia.com/medias/7phpe910v3");
    this.previewEmbedded = false;
    this.change = false;
    return this.debounceUpdates();
  };

  VideoInEmail.prototype.clearAll = function() {
    $("#source_embed_code").val("");
    this.previewEmbedded = false;
    this.change = false;
    return this.debounceUpdates();
  };

  VideoInEmail.prototype.updateEmbedWidth = function(newWidth) {
    var newEmbed, newHeight, oldHeight, oldWidth;
    oldHeight = Wistia.EmbedCode.parse($("#source_embed_code").val()).height();
    oldWidth = Wistia.EmbedCode.parse($("#source_embed_code").val()).width();
    newHeight = Math.round(oldHeight * newWidth / oldWidth);
    newEmbed = Wistia.EmbedCode.parse($("#source_embed_code").val()).width(newWidth).height(newHeight);
    return $("#source_embed_code").val(newEmbed);
  };

  VideoInEmail.prototype.debounceUpdates = function() {
    var updateOutputTimeout;
    clearTimeout("updateOutputTimeout");
    return updateOutputTimeout = setTimeout(this.updateOutput, 100);
  };

  VideoInEmail.prototype.updateOutput = function() {
    this.sourceEmbedCode = Wistia.EmbedCode.parse($("#source_embed_code").val());
    if (this.sourceEmbedCode && this.sourceEmbedCode.isValid()) {
      this.width = this.getVideoWidth();
      this.updatePreview();
      return this.updateVideoCode();
    } else {
      $("#video_code").val("Please enter a valid Wistia embed code.");
      return $("#preview").html("<div id=\"placeholder_preview\">Your video here</div>");
    }
  };

  VideoInEmail.prototype.updatePreview = function() {
    var _this = this;
    return Wistia.timeout("updatePreview", function() {
      if (_this.change) {

      } else if (!_this.previewEmbedded) {
        return _this.sourceEmbedCode.previewInElem("preview", {
          type: "api"
        }, function() {
          return _this.previewEmbedded = true;
        });
      }
    }, 100);
  };

  VideoInEmail.prototype.updateVideoCode = function() {
    var hashedId,
      _this = this;
    hashedId = Wistia.EmbedCode.parse($("#source_embed_code").val()).hashedId();
    return Wistia.remote.media(hashedId, function(media) {
      var mp4Url, playerColor, posterUrl, styles;
      mp4Url = media.assets.iphone.url.replace('.bin', '/video.mp4');
      posterUrl = media.assets.still.url;
      playerColor = media.embed_options.playerColor;
      $('#video_code').val(_this.outputVideoCode(_this.getVideoWidth(), posterUrl, mp4Url, _this.getFallbackLink(), posterUrl, playerColor));
      styles = {
        height: '200px',
        width: '585px',
        'font-family': 'Courier'
      };
      return $('#video_code').css(styles);
    });
  };

  VideoInEmail.prototype.outputVideoCode = function(width, poster, mp4, fallbackLink, fallbackImage, playerColor) {
    return "<video width=\"" + width + "\" poster=\"" + poster + "\" controls=\"controls\">\n  <source src=\"" + mp4 + "\" type=\"video/mp4\"/>\n  <a href=\"" + fallbackLink + "\"><img src=\"" + (fallbackImage.replace('.bin', '.jpg')) + "?image_play_button=true&image_play_button_color=" + playerColor + "&image_resize=" + width + "\" width=\"" + width + "\"/></a>\n</video>";
  };

  VideoInEmail.prototype.getVideoWidth = function() {
    return parseInt($("#video_width").val());
  };

  VideoInEmail.prototype.getFallbackLink = function() {
    return $("#fallback_link").val();
  };

  return VideoInEmail;

})();

window.setupLabInterface = function($) {
  return $(function() {
    window.videoInEmail = new VideoInEmail();
    if (!Wistia.localStorage("videoInEmail.cleared")) {
      showExample();
      $(".show_example_text").hide();
      $(".clear_example_text").show();
    } else {
      $(".show_example_text").show();
      $(".clear_example_text").hide();
    }
    $("#clear_example").click(function(event) {
      event.preventDefault();
      resetInterface();
      $(".show_example_text").show();
      $(".clear_example_text").hide();
      return Wistia.localStorage("videoInEmail.cleared", true);
    });
    return $("#show_example").click(function(event) {
      event.preventDefault();
      showExample();
      $(".show_example_text").hide();
      $(".clear_example_text").show();
      return Wistia.localStorage("videoInEmail.cleared", false);
    });
  });
};

window.resetInterface = function() {
  return videoInEmail.clearAll();
};

window.showExample = function() {
  return videoInEmail.setupExample();
};

setupLabInterface(jQuery);
